public enum EditMode
{
    DeleteField,
    WallField,
    StartField,
    GoalField,
    CheckpointField,
    OneWayField,
    Conveyor,
    Water,
    Ice,
    Void,
    GrayKeyDoorField,
    RedKeyDoorField,
    GreenKeyDoorField,
    BlueKeyDoorField,
    YellowKeyDoorField,
    Player,
    Anchor,
    AnchorBall,
    BallDefault,
    BallCircle,
    Coin,
    GrayKey,
    RedKey,
    GreenKey,
    BlueKey,
    YellowKey
}

public enum FieldType
{
    WallField,
    StartField,
    GoalField,
    CheckpointField,
    OneWayField,
    Conveyor,
    Water,
    Ice,
    Void,
    GrayKeyDoorField,
    RedKeyDoorField,
    GreenKeyDoorField,
    BlueKeyDoorField,
    YellowKeyDoorField
}